# Generated by Django 3.1.2 on 2020-11-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='airport',
        ),
    ]
