# Generated by Django 3.1.2 on 2020-11-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_delete_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IATA', models.CharField(max_length=4)),
                ('IACO', models.CharField(max_length=4)),
                ('Airport_Name', models.TextField()),
                ('Location', models.TextField()),
                ('GPS', models.TextField()),
            ],
        ),
    ]
