# Generated by Django 3.1.2 on 2020-11-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_airport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='IACO',
            new_name='iaco',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='IATA',
            new_name='iata',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='Airport_Name',
            new_name='name',
        ),
    ]
