# Generated by Django 3.1.2 on 2020-11-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201113_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='GPS',
            new_name='gps',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='Location',
            new_name='location',
        ),
    ]
