# Generated by Django 3.1.2 on 2020-11-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201113_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
