# Generated by Django 3.1.2 on 2020-11-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0008_delete_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=4)),
                ('iaco', models.CharField(max_length=4)),
                ('airport_name', models.TextField()),
                ('location', models.TextField()),
                ('gps', models.TextField()),
            ],
        ),
    ]
