# Generated by Django 3.1.2 on 2020-11-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_airport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='iaco',
            new_name='icao',
        ),
    ]
