# Generated by Django 3.1.2 on 2020-11-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201113_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
